// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDux4AKGkoQh74PJOz6OzaoxDRHrfGt3o0',
    appId: '1:417095592775:web:46f22b08fcfd0683ebba62',
    messagingSenderId: '417095592775',
    projectId: 'jobsucheema2025',
    authDomain: 'jobsucheema2025.firebaseapp.com',
    storageBucket: 'jobsucheema2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRIcBzDFVPOB632uLbrCS970MFu_ebUfY',
    appId: '1:417095592775:android:2c9accc411c67812ebba62',
    messagingSenderId: '417095592775',
    projectId: 'jobsucheema2025',
    storageBucket: 'jobsucheema2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASAmdc9nJXxzGMG38L8bFLCMBaRZHI9Mg',
    appId: '1:417095592775:ios:64fc8be06930794aebba62',
    messagingSenderId: '417095592775',
    projectId: 'jobsucheema2025',
    storageBucket: 'jobsucheema2025.firebasestorage.app',
    iosBundleId: 'com.example.jobSuche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASAmdc9nJXxzGMG38L8bFLCMBaRZHI9Mg',
    appId: '1:417095592775:ios:64fc8be06930794aebba62',
    messagingSenderId: '417095592775',
    projectId: 'jobsucheema2025',
    storageBucket: 'jobsucheema2025.firebasestorage.app',
    iosBundleId: 'com.example.jobSuche',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDux4AKGkoQh74PJOz6OzaoxDRHrfGt3o0',
    appId: '1:417095592775:web:2a2deeee93c76f85ebba62',
    messagingSenderId: '417095592775',
    projectId: 'jobsucheema2025',
    authDomain: 'jobsucheema2025.firebaseapp.com',
    storageBucket: 'jobsucheema2025.firebasestorage.app',
  );
}
